apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app
  namespace: flask
  labels:
    app: two-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: flaskapp
          image: dattarahegaonkar09/flaskapp:latest
          env:
            - name: MYSQL_HOST
              value: "10.96.249.1"          # this is your mysql's service clusture IP, Make sure to change it with yours
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "flaskdb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
